import 'course.dart';

List<Course> courses = [
  Course(
    id: 1,
    title: 'Graphics Design',
    imageUrl: 'assets/images/graphic_designing.png',
    charges: 0,
    duration: 6,
    classes: 'Mon-Fri',
    lecture: 'On Campus',
    program: 'NUTECH',
    chargesUnit: 'Free',
    durationUnit: 'Months',
    modules: [],
  ),
  Course(
      id: 1,
      title: 'Graphics Design',
      imageUrl: 'assets/images/graphic_designing.png',
      charges: 0,
      duration: 6,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: 'Free',
      durationUnit: 'Months',
      modules: []),
  Course(
      id: 1,
      title: 'Graphics Design',
      imageUrl: 'assets/images/graphic_designing.png',
      charges: 0,
      duration: 6,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: 'Free',
      durationUnit: 'Months',
      modules: []),
  Course(
      id: 1,
      title: 'Graphics Design',
      imageUrl: 'assets/images/graphic_designing.png',
      charges: 0,
      duration: 6,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: 'Free',
      durationUnit: 'Months',
      modules: []),
  Course(
      id: 1,
      title: 'Graphics Design',
      imageUrl: 'assets/images/graphic_designing.png',
      charges: 0,
      duration: 6,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: 'Free',
      durationUnit: 'Months',
      modules: []),
  Course(
      id: 2,
      title: 'Mobile App Design',
      imageUrl: 'assets/images/mobile_app_design.png',
      charges: 3500,
      duration: 1,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: '/Month',
      durationUnit: 'Year',
      modules: [
        'Introduction to Microsoft Office',
        'Basic Concepts of Database',
        'Dart Programming Language',
        'Flutter Application Development'
      ]),
  Course(
      id: 3,
      title: 'Game Development',
      imageUrl: 'assets/images/game_development.png',
      charges: 7000,
      duration: 8,
      classes: 'Mon-Fri',
      lecture: 'On Campus',
      program: 'NUTECH',
      chargesUnit: '/Month',
      durationUnit: ' Months',
      modules: []),
];
